from rest_framework import serializers
from .models import MhadaPlot

class MhadaPlotSerializer(serializers.Serializer):
    gid = serializers.IntegerField(read_only=True)
    state = serializers.CharField(read_only=True, allow_null=True)
    district = serializers.CharField(read_only=True, allow_null=True)
    tehsil = serializers.CharField(read_only=True, allow_null=True)
    municipal_corporation = serializers.CharField(read_only=True, allow_null=True)
    ward = serializers.CharField(read_only=True, allow_null=True)
    layout = serializers.CharField(read_only=True, allow_null=True)
    plot_number = serializers.CharField(read_only=True, allow_null=True)
    occupant = serializers.CharField(read_only=True, allow_null=True)
    first_allottee = serializers.CharField(read_only=True, allow_null=True)
    owner_name = serializers.CharField(read_only=True, allow_null=True)
    type_of_code = serializers.CharField(read_only=True, allow_null=True)
    category = serializers.CharField(read_only=True, allow_null=True)
    land_use = serializers.CharField(read_only=True, allow_null=True)
    color_code = serializers.CharField(read_only=True, allow_null=True)
    room_no = serializers.CharField(read_only=True, allow_null=True)
    structure_type = serializers.CharField(read_only=True, allow_null=True)
    grflr_area = serializers.FloatField(read_only=True, allow_null=True)
    first_flr_area = serializers.FloatField(read_only=True, allow_null=True)
    second_flr_area = serializers.FloatField(read_only=True, allow_null=True)
    total_area = serializers.FloatField(read_only=True, allow_null=True)
    area_sqm = serializers.FloatField(read_only=True, allow_null=True)
    mhada_transfer_order = serializers.CharField(read_only=True, allow_null=True)
    transfer_status = serializers.CharField(read_only=True, allow_null=True)
    possession_date = serializers.CharField(read_only=True, allow_null=True)
    mhada_transfer = serializers.CharField(read_only=True, allow_null=True)
    status = serializers.CharField(read_only=True, allow_null=True)
    centroid_json = serializers.CharField(read_only=True, allow_null=True)
    polygon_json = serializers.CharField(read_only=True, allow_null=True)
